version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bookstore-network
  # El Gateway (Nginx)
  gateway:
    image: nginx:stable-alpine
    ports:
      - "8080:80" # Mapeamos el puerto 8080 de tu PC al 80 de Nginx
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - chat-service
    networks:
      - bookstore-network

  # Microservicio de Autenticaci√≥n
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght
    depends_on:
      - auth-db
    networks:
      - bookstore-network

  # Base de Datos para Auth
  auth-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432" # Mapeamos un puerto externo diferente para evitar conflictos
    networks:
      - bookstore-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  # Base de Datos de Prueba para Auth
  auth-test-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_test_db
    ports:
      - "5434:5432"
    networks:
      - bookstore-network
    volumes:
      - auth-test-db-data:/var/lib/postgresql/data

  # Microservicio de Libros
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://user:password@book-db:5432/book_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght
    depends_on:
      - book-db
    networks:
      - bookstore-network

  # Base de Datos para Books
  book-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_db
    ports:
      - "5435:5432"
    networks:
      - bookstore-network
    volumes:
      - book-db-data:/var/lib/postgresql/data

  # Microservicio de Chat
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    environment:
      - PORT=5005
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght_mysecretpassword256lenght
    ports:
      - "5005:5005"
    depends_on:
      - redis
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  auth-db-data:
  auth-test-db-data:
  book-db-data:
